services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - PORT=8080
      - FILES_STORAGE_PATH=/app/storage/files
      - DATABASE_URL=host=db user=postgres password=postgres dbname=hits_classroom port=5432 sslmode=disable TimeZone=UTC
    volumes:
      - file_storage:/app/storage/files
    depends_on:
      db:
        condition: service_healthy
      file-storage:
        condition: service_started

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hits_classroom
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  file-storage:
    image: busybox
    volumes:
      - file_storage:/storage
    command: sh -c "mkdir -p /storage && sleep infinity"

volumes:
  file_storage:
    driver: local
  pg_data:
    driver: local
